run:
  deadline: 90s
output:
  format: line-number
linters:
  enable:
    - bodyclose
    - dupl
    - gochecknoinits
    - gocognit
    - goconst
    - gocyclo
    - golint
    - gosec
    - maligned
    - nakedret
    - prealloc
    - scopelint
    - stylecheck
    - unconvert
    - unparam
issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - dupl
        - gocognit
        - scopelint
